import jsPDF from 'jspdf'

export const generateBusinessReport = () => {
  const doc = new jsPDF()
  
  // Add company header
  doc.setFontSize(24)
  doc.setTextColor(67, 56, 202) // Primary color
  doc.text('Business Hub', 20, 30)
  
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Monthly Performance Report', 20, 45)
  
  // Add date
  doc.setFontSize(10)
  doc.setTextColor(128, 128, 128)
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
  doc.text(`Generated on ${currentDate}`, 20, 55)
  
  // Key Metrics Section
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Key Performance Metrics', 20, 75)
  
  const metrics = [
    { label: 'Total Revenue', value: '$12,426', change: '+12.5%' },
    { label: 'Active Customers', value: '1,247', change: '+8.2%' },
    { label: 'Chat Conversations', value: '436', change: '+23.1%' },
    { label: 'Conversion Rate', value: '12.8%', change: '+2.4%' }
  ]
  
  let yPos = 90
  metrics.forEach((metric) => {
    doc.setFontSize(11)
    doc.setTextColor(0, 0, 0)
    doc.text(`${metric.label}:`, 25, yPos)
    doc.text(metric.value, 100, yPos)
    doc.setTextColor(34, 197, 94) // Success green
    doc.text(metric.change, 140, yPos)
    yPos += 15
  })
  
  // Services Performance Section
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Service Performance', 20, yPos + 10)
  
  const services = [
    { name: 'Hair Cut & Style', bookings: 23, revenue: '$1,035' },
    { name: 'Manicure & Pedicure', bookings: 18, revenue: '$630' },
    { name: 'Facial Treatment', bookings: 12, revenue: '$900' },
    { name: 'Massage Therapy', bookings: 8, revenue: '$680' }
  ]
  
  yPos += 25
  services.forEach((service) => {
    doc.setFontSize(10)
    doc.setTextColor(0, 0, 0)
    doc.text(service.name, 25, yPos)
    doc.text(`${service.bookings} bookings`, 100, yPos)
    doc.text(service.revenue, 150, yPos)
    yPos += 12
  })
  
  // Customer Insights Section
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Customer Insights', 20, yPos + 15)
  
  const insights = [
    'New Customers: +23 this month',
    'Returning Customers: 87%',
    'Average Booking Value: $52',
    'Customer Lifetime Value: $342',
    'Peak Hours: 2-4 PM weekdays',
    'Most Popular Day: Saturday'
  ]
  
  yPos += 30
  insights.forEach((insight) => {
    doc.setFontSize(10)
    doc.text(`• ${insight}`, 25, yPos)
    yPos += 10
  })
  
  // Footer
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by Business Hub Analytics', 20, 280)
  doc.text('© 2024 Business Hub. All rights reserved.', 20, 290)
  
  // Save the PDF
  doc.save(`business-report-${new Date().toISOString().split('T')[0]}.pdf`)
}